name: Mirror and run GitLab CI

on:
  push:
    branches: main

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://gitlab.unige.ch/grand_siecle/data_alto.git'
            GIT_USERNAME: rayondemiel
            GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
            PUSH_ALL_REFS: "false"
