name: Mirror and run GitLab CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.unige.ch/grand_siecle/data_alto"
      env:
        FOLLOW_TAGS: "true"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.unige.ch"
        GITLAB_USERNAME: "rayondemiel"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "8878"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
